name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & Test on ${{ matrix.os }} with Swift 5.10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Swift
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: '5.10'

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test
